### ISSUE TITLE
No file RF24/RF24.h

### ISSUE THREAD

**Issue by OrkDev1** [aarossig/nerfnet#4]
Hi, first of all, nerfnet is a great work but I couldn't find a solution to this error. Any Idea?
![Screenshot_1](https://user-images.githubusercontent.com/63416552/112734226-77cf5280-8f55-11eb-9515-d8e87946d7c0.png)
This happens when I type "sudo make -j4"
Thanks in advance

**Comment by aarossig** [comment]
You need to install RF24 separately as well. Perhaps I should make that clear in the README. Try this after cloning the RF24 repo:

https://github.com/nRF24/RF24

```
cd RF24/
make clean
./configure --driver=SPIDEV; make -j4; sudo make install
```

**Comment by OrkDev1** [comment]
Thank you, it successfully built and yes you probably should add that to the README for raspberry pi beginners like me.
And I have another problem. Even though it built the sudo nerfnet command does not work.
![Screenshot_2](https://user-images.githubusercontent.com/63416552/112745786-88161a80-8fb3-11eb-9477-b3acbe97512c.png)

**Comment by aarossig** [comment]
Oh that is simple - you to add a leading `./` to the binary name to let your shell know to execute the binary in the current directory rather than searching on your `PATH` variable (ie: `/usr/bin`, etc).

Example: `sudo ./nerfnet --primary`

**Comment by OrkDev1** [comment]
Ok all done, thank you very much. This is a great work and I hope to see more Thanks Again
